version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - MONGO_URI=mongodb+srv://emm:emm@cluster0-9jokw.gcp.mongodb.net/ren-banking?retryWrites=true&w=majority
      - NODE_ENV=production
      - JWT_SECRET=jwtPrivateKey
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
