version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - MONGO_URI=mongodb+srv://emm:emm@cluster0-9jokw.gcp.mongodb.net/ren-banking?retryWrites=true&w=majority
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
